In [14]:
import matplotlib.font_manager as fm
import numpy as np

# font_list = fm.findSystemFonts(fontext = 'ttf')
# for f in font_list :
#     print(f)

font_list2 = fm.fontManager.ttflist
for f in font_list2 :
    print(f)

<Font 'DejaVu Serif' (DejaVuSerif-BoldItalic.ttf) italic normal 700 normal>
<Font 'DejaVu Sans' (DejaVuSans-Bold.ttf) normal normal 700 normal>
<Font 'cmb10' (cmb10.ttf) normal normal 400 normal>
<Font 'STIXSizeThreeSym' (STIXSizThreeSymBol.ttf) normal normal 700 normal>
<Font 'DejaVu Sans' (DejaVuSans.ttf) normal normal 400 normal>
<Font 'STIXGeneral' (STIXGeneralBolIta.ttf) italic normal 700 normal>
<Font 'DejaVu Sans Mono' (DejaVuSansMono-BoldOblique.ttf) oblique normal 700 normal>
<Font 'STIXGeneral' (STIXGeneralBol.ttf) normal normal 700 normal>
<Font 'STIXSizeFourSym' (STIXSizFourSymBol.ttf) normal normal 700 normal>
<Font 'STIXSizeThreeSym' (STIXSizThreeSymReg.ttf) normal normal 400 normal>
<Font 'DejaVu Serif' (DejaVuSerif-Italic.ttf) italic normal 400 normal>
<Font 'cmex10' (cmex10.ttf) normal normal 400 normal>
<Font 'DejaVu Sans Mono' (DejaVuSansMono.ttf) normal normal 400 normal>
<Font 'DejaVu Sans' (DejaVuSans-Oblique.ttf) oblique normal 400 normal>
<Font 'STIXGeneral' (ST

In [11]:
a = np.random.randint(0, 10, (2, 3))
print(a)
np.savetxt("./data/score.csv",a)

[[7 3 9]
 [3 0 0]]


In [12]:
b = np.loadtxt("./data/score.csv",np.int32)
print(b)

[[7 3 9]
 [3 0 0]]


In [15]:
! pip install wordcloud

  Running setup.py clean for wordcloud
Failed to build wordcloud
    Running setup.py install for wordcloud: started
    Running setup.py install for wordcloud: finished with status 'error'


  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\BIT\anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\BIT\\AppData\\Local\\Temp\\pip-install-occil5b4\\wordcloud_a71b9267692e49e38fd9bc5d481d31ae\\setup.py'"'"'; __file__='"'"'C:\\Users\\BIT\\AppData\\Local\\Temp\\pip-install-occil5b4\\wordcloud_a71b9267692e49e38fd9bc5d481d31ae\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\BIT\AppData\Local\Temp\pip-wheel-5s7glgk9'
       cwd: C:\Users\BIT\AppData\Local\Temp\pip-install-occil5b4\wordcloud_a71b9267692e49e38fd9bc5d481d31ae\
  Complete output (20 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creatin